server:
  port: 8079
logging:
  level:
    root: info
spring:
  application:
    name: java-jpa
  jpa:
    database: h2
    #defer-datasource-initialization: true
    #show-sql: true
    #format_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
